#!/usr/bin/bash
echo ""
echo ""
echo ""
echo "===================================================================================="
echo "***********************Start installer.sh for Plot juggler...***********************"
echo "===================================================================================="
echo ""
echo ""
echo ""
echo ""
echo ""
echo "***********************Check bashrc...***********************"
echo ""
echo ""
echo ""
﻿basrc="/home/$USER/.bashrc.bak"
if [ -e $﻿basrc ]; then
    echo "***********************$﻿basrc is already changed. then skip***********************"
    echo ""
    echo ""
    echo ""
else
    echo "*********************** $﻿basrc is need to add new command line!***********************"
    echo ""
    echo ""
    echo ""
    echo "*********************** Add new command line in $﻿basrc...***********************"
    echo ""
    echo ""
    echo ""
    mv /home/$USER/.bashrc /home/$USER/.bashrc.bak;
    mv /home/$USER/tools/plot_installer/.bashrc /home/$USER/.bashrc;
    echo "*********************** Add new command line in $﻿basrc***********************[[complete!!]]"
    echo ""
    echo ""
    echo ""
fi
echo "======================================================================="
echo "***********************Add SSH KEY's for SHKO...***********************"
echo "======================================================================="
echo ""
echo ""
echo ""
echo ""
echo ""
echo "***********************Check id_rsa & id_rsa_pub...***********************"
echo ""
echo ""
echo ""
﻿id_rsa="/home/$USER/.comma/persist/comma/id_rsa"
if [ -e $﻿id_rsa ]; then
    echo "***********************$﻿id_rsa exists. then skip***********************"
    echo ""
    echo ""
    echo ""
else
    echo "*********************** Add new commandline in $﻿id_rsa...***********************"
    echo ""
    echo ""
echo ""
